config/routes.rb
Rails.application.routes.draw do
  
  resources :innovations
  resources :chorus do 
    collection do 
      post 'import' => 'chorus#import'
     
    end
  end 
 
  devise_for :users, :path => "",
    :path_names =>  {:sign_in => "connexion", :sign_out => "deconnexion"}
  ActiveAdmin.routes(self)
  resources :ouvrages_financements do 
    collection {post :import}
  end
  resources :ouvrages_depenses do 
    collection do 
      post 'import' => 'ouvrages_depenses#import'
    end
  end 
  resources :solideo_depenses do 
    collection do 
      post 'import_structure' => 'solideo_depenses#import_structure'
      post 'import_depenses' => 'solideo_depenses#import_depenses'
    end 
  end
  resources :solideo_financements do 
    collection do 
      post 'import' => 'solideo_financements#import'
      post 'import2' => 'solideo_financements#import2'
      post 'deleteall' => 'solideo_financements#delete_financements'
      post 'import_financeur' => 'solideo_financements#import_financeur'
      post 'import_financements' => 'solideo_financements#import_financements'
    end 
    
  end 

  resources :etat_budgets
  resources :etat_depenses do 
    collection do 
      post 'import' => 'etat_depenses#import'
    end 
  end
  resources :ouvrages do 
    collection {post :import}
  end 
  resources :documents

  resources :innovations do 
    collection do 
      post 'import' => 'innovations#import'
      post 'import2' => 'innovations#import2'
      post 'import_categorie' => 'innovations#import_categorie'
    end 
  end
  get '/new-versement'=>'innovations#new_versement'
  get '/new-categorie'=>'innovations#new_categorie'
  root 'pages#home'
  
  get 'documents-solideo' => 'documents#documents_solideo'

  get 'new_structure' => 'solideo_depenses#new_structure'
  get 'new_financeur' => 'solideo_financements#new_financeur'
  
  get 'etat_depenses_filter' => 'etat_depenses#index_filter'
  get 'solideo_financements_filter' => 'solideo_financements#index_filter'
  
  
  get 'recherche-ouvrages' => 'ouvrages#search'
  get 'recherche-projets' => 'innovations#search'
  post 'delete-document' => 'documents#delete_file'
  
  get 'timeline' => 'ouvrages#timeline'
  get 'risques' => 'ouvrages#risques'
  post 'select_bop' => 'chorus#select_bop'
  post 'select_uo' => 'chorus#select_uo'
   post 'select_date_programme' => 'chorus#select_date_programme'
  post 'select_action' => 'chorus#select_action'
  get 'new_nom' => 'chorus#new_nom'
   post 'import_nom' => 'chorus#import_nom'
  get 'search_choru' => "chorus#search_choru"
  
  post 'import_maquette' => "ouvrages_depenses#import_maquette"

  
  post 'update_file' => 'ouvrages#update_file'
  get 'les-jop2024' => 'pages#jop2024'
  get 'synthese' => "pages#synthese"
  get 'reporting' => "pages#reporting"

  get 'mentions-legales' => "pages#mentions"
  get 'accessibilite' => "pages#accessibilite"
  get 'public' => "pages#public"
  get 'utilisation-budget' => 'pages#interets'
  get 'impacts' => 'pages#impacts'
  post 'maquette-date' => 'ouvrages_depenses#maquette_date'

  post 'form-edit' => 'innovations#form_edit'

  post 'import_disciplines' => "pages#import_disciplines"
  get 'new-disciplines' => "pages#new_disciplines"
  post 'import_ouvrages_publics' => "pages#import_ouvrages_publics"
  get 'new-ouvrages-publics' => "pages#new_ouvrages_publics"

  get 'recherche-ouvrages-publics' => 'pages#search_ouvrages_publics'

  post 'supp' => 'chorus#supp'
  post 'sort_table_programme' => "chorus#sort_table_programme"

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/solideo_financement.rb
class SolideoFinancement < ApplicationRecord
  require 'csv'
  
  def self.import(file)
    CSV.foreach(file.path) do |row|
      @solideofinancement=SolideoFinancement.new
      @solideofinancement.financeur = row[0]
      @solideofinancement.montant = row[1]
      @solideofinancement.date = row[2]
      if !@solideofinancement.montant.nil?
        @solideofinancement.save
      end 
    end 
  end
  
  def self.import2(file, date_year, date_month)
    @financeurs = ["","privé", "Etat", "RIF", "Ville de Paris", "Métropole Grand Paris", "CD92", "CD93", "CD78", "EPT Plaine Commune","EPT Terres d'envol", "Ville de Dugny", "Ville du Bourget", "CASQY", "Ville de Marseille"]
  end
end

app/controllers/solideo_financements_controller.rb
class SolideoFinancementsController < ApplicationController
  before_action :set_solideo_financement, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!
  # GET /solideo_financements
  # GET /solideo_financements.json
  def index
     @nav=true
  
    if SolideoFinanceurFinancement.count > 0
      @etat = SolideoFinanceur.where(name: "Etat").first
      @financements_etat = SolideoFinanceurFinancement.where(solideo_financeur_id: @etat.id).where('date = ?',SolideoFinanceurFinancement.order(date: :asc).last.date).sum('encaissements')
      @financements_etat_global = SolideoFinanceurBudget.where(solideo_financeur_id: @etat.id).where('date = ?',SolideoFinanceurFinancement.order(date: :asc).last.date).sum('financement_global')

      @collectivites = SolideoFinanceur.where('categorie = ? AND name != ?','SUBVENTION', "Etat").pluck(:id)
      @financements_collectivites = SolideoFinanceurFinancement.where(solideo_financeur_id: @collectivites).where('date = ?',SolideoFinanceurFinancement.order(date: :asc).last.date).sum('encaissements')
      @financements_collectivites_global = SolideoFinanceurBudget.where(solideo_financeur_id: @collectivites).where('date = ?',SolideoFinanceurFinancement.order(date: :asc).last.date).sum('financement_global')

      @recettes = SolideoFinanceur.where(categorie: "RECETTES HPF")
      @financements_recettes = SolideoFinanceurFinancement.where(solideo_financeur_id: @recettes).where('date = ?',SolideoFinanceurFinancement.order(date: :asc).last.date).sum('encaissements')
      @financements_recettes_global = SolideoFinanceurBudget.where(solideo_financeur_id: @recettes).where('date = ?',SolideoFinanceurFinancement.order(date: :asc).last.date).sum('financement_global')

      @paris = SolideoFinanceur.where(categorie: "PARIS 2024")
      @financements_paris = SolideoFinanceurFinancement.where(solideo_financeur_id: @paris).where('date = ?',SolideoFinanceurFinancement.order(date: :asc).last.date).sum('encaissements')
      @financements_paris_global = SolideoFinanceurBudget.where(solideo_financeur_id: @paris).where('date = ?',SolideoFinanceurFinancement.order(date: :asc).last.date).sum('financement_global')

      @dates_financements_reporting = SolideoFinanceurFinancement.order('date DESC').pluck(:date).uniq

    end
  end
  
  def index_filter
     respond_to do |format|
      format.js
    end
  end 

  # GET /solideo_financements/1
  # GET /solideo_financements/1.json
  def show
  end 

  # GET /solideo_financements/new
  def new
    @solideo_financement = SolideoFinancement.new
  end

  # GET /solideo_financements/1/edit
  def edit
  end
  
  def import
    SolideoFinancement.import(params[:file])
    redirect_to solideo_financements_path  
  end
  def import2
    SolideoFinancement.import2(params[:file], params[:date_year].to_i, params[:date_month].to_i)
    OuvragesFinancement.import_ouvrage2(params[:file], params[:date_year].to_i, params[:date_month].to_i)
    redirect_to solideo_financements_path    
  end
  
  def delete_financements
    @solideo_financements = SolideoFinancement.where('date = ?', params[:date])
    @solideo_financements.all.destroy_all
    @ouvrages_financements = OuvragesFinancement.where('date = ? ', params[:date])
    @ouvrages_financements.all.destroy_all
    redirect_to new_solideo_financement_path 
  end  
  

  # POST /solideo_financements
  # POST /solideo_financements.json
  def create
    @solideo_financement = SolideoFinancement.new(solideo_financement_params)

    respond_to do |format|
      if @solideo_financement.save
        format.html { redirect_to @solideo_financement, notice: 'Solideo financement was successfully created.' }
        format.json { render :show, status: :created, location: @solideo_financement }
      else
        format.html { render :new }
        format.json { render json: @solideo_financement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solideo_financements/1
  # PATCH/PUT /solideo_financements/1.json
  def update
    respond_to do |format|
      if @solideo_financement.update(solideo_financement_params)
        format.html { redirect_to @solideo_financement, notice: 'Solideo financement was successfully updated.' }
        format.json { render :show, status: :ok, location: @solideo_financement }
      else
        format.html { render :edit }
        format.json { render json: @solideo_financement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solideo_financements/1
  # DELETE /solideo_financements/1.json
  def destroy
    @solideo_financement.destroy
    respond_to do |format|
      format.html { redirect_to solideo_financements_url, notice: 'Solideo financement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def new_financeur
  end
  def import_financeur
    SolideoFinanceur.import(params[:file])
    redirect_to solideo_financements_path
  end 
  def import_financements
    SolideoFinanceurFinancement.import(params[:file])
    redirect_to solideo_financements_path
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solideo_financement
      @solideo_financement = SolideoFinancement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def solideo_financement_params
      params.require(:solideo_financement).permit(:financeur, :date, :montant_prevu, :montant, :categorie)
    end
end

app/helpers/solideo_financements_helper.rb
module SolideoFinancementsHelper
end

app/views/solideo_financements/_filtres.html.erb
<div class="modal fade" id="financementsfiltres" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content modal-content-search-filtres" >
      <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <p class="modal-title modal_title" id="exampleModalLabel">Filtres <i class="fas fa-sliders-h"></i></p>
    
      </div>
      
      <div class="modal-body">
        <%= form_tag solideo_financements_filter_path, method: :get, remote: true do %>
        <div class="modal-search-filters-form-title">
          Financeur 
        </div>
        <div  class="modal-search-filters-form">
          
          <label> <%= check_box_tag 'financeur[]', "solideo", false%> Etat</label>
          <label><%= check_box_tag 'financeur[]', "cojo", false%> Collectivités</label>
          <label><%= check_box_tag 'financeur[]', "hauteperformance", false%> Privés</label>
        </div>
        <div class="modal-search-filters-form-title">
          Dates
        </div>
        <div class="modal-search-filters-form">
          <label><%= check_box_tag 'dates[]', "2018", false%> 2018</label>
          <label><%= check_box_tag 'dates[]', "2019", false%> 2019</label>
          <label><%= check_box_tag 'dates[]', "2020", false%> 2020</label>
          <label><%= check_box_tag 'dates[]', "2021", false%> 2021</label>
          <label><%= check_box_tag 'dates[]', "2022", false%> 2022</label>
          <label><%= check_box_tag 'dates[]', "2023", false%> 2023</label>
          <label><%= check_box_tag 'dates[]', "2024", false%> 2024</label>
          <label><%= check_box_tag 'dates[]', "2025", false%> 2025</label>
        </div>
       
     
        
        <div class="modal-search-filters-form-btn">
          <%= submit_tag "Filtrer", id: "close-modal" %>  
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>

$('#close-modal').click(function() {
    $('#financementsfiltres').modal('hide');
});
$('input').attr('checked', false); 

 $('input').change(function()
      {
        if ($(this).is(':checked')) {
           $(this).parent().addClass('modal-search-filters-form-active');
        }else{
           $(this).parent().removeClass('modal-search-filters-form-active');
        };
      });
  
</script>

app/views/solideo_financements/_form.html.erb
<div class="ED_new_form_box">
<%= form_with(model: solideo_financement, local: true) do |form| %>
  <% if solideo_financement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(solideo_financement.errors.count, "error") %> prohibited this solideo_financement from being saved:</h2>

      <ul>
      <% solideo_financement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="SD_new_form_field SD_new_form_field_date">
    <%= form.label :date %>
    <%= form.date_select :date, {:order => [:year]}, class: "SD_new_form_input_date"   %>
  </div>
  
  <div class="SD_new_form_field">
    <%= form.label :financeur %>
    <%= form.select :financeur,   [["Financement","privé"], [ "Etat", "Etat"], ["RIF", "RIF"], ["Ville de Paris","Ville de Paris"], ["Métropole Grand Paris","Métropole Grand Paris"], ["CD92", "CD92"], ["CD93", "CD93"], ["CD78","CD78"], ["EPT Plaine Commune","EPT Plaine Commune"], ["EPT Terres d'envol","EPT Terres d'envol"], ["Ville de Dugny","Ville de Dugny"],[ "Ville du Bourget","Ville du Bourget"], [ "CASQY","CASQY"], [ "Ville de Marseille","Ville de Marseille"]]
 %>
  </div>

  <div class="SD_new_form_field">
    <%= form.label :montant_prevu %>
    <%= form.text_field :montant_prevu %>
  </div>
  
   <div class="SD_new_form_field">
    <%= form.label :montant %>
    <%= form.text_field :montant %>
  </div>

   <div class="ED_new_form_field ED_new_form_field_beneficiaire">
    <%= form.label :categorie, "Catégorie"%>
    <%= form.select :categorie, [["Ouvrages","ouvrages"],["Reserve", "reserve"],["Frais de fonctionnement","Fonctionnement"], ["Innovation","innovation"]], {}, class: "ED_new_form_input_beneficiaire" %>
  </div>
  
  <div class="SD_new_form_field_submit">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/solideo_financements/edit.html.erb
<h1>Editing Solideo Financement</h1>

<%= render 'form', solideo_financement: @solideo_financement %>

<%= link_to 'Show', @solideo_financement %> |
<%= link_to 'Back', solideo_financements_path %>

app/views/solideo_financements/index.html.erb
<div class="page_w">
 <div class="i24"></div>
  <div class="titre_page text-center">Les financements de la Solideo </div>
  <div class="i40"></div>

   <%= render 'topo'%>

</div>


<script>

  $('.menu-solideo-finances').addClass('menu-active2'); 
  $('.menu-solideo').addClass('menu-active'); 

  $('#MonCollapse').addClass('in'); 

</script>

app/views/solideo_financements/index_filter.js.erb
$('#table_filtres').html("<%=j render 'solideo_financements/table' %>")

app/views/solideo_financements/new.html.erb
<div class="page_w">
  <div class="i24"></div>
  <div class="titre_page text-center">Ajouter un nouveau document</div>
  <div class="i40"></div>
  <div class="ED_new_form_box">

    <%=form_tag import_solideo_financements_path, multipart: true do %>

      <div class="document-file-input">
          <label><%= file_field_tag :file, accept: '.csv'  %>
            <div class="document-type"><i class="far fa-file-pdf"></i> </div>
            <div class="input-text"><i class="fas fa-plus-circle"></i><br>Ajouter un document</div>
            <div class="document-check">
            <i class="fas fa-check-circle"></i>
          </div>
          </label>
          
        <div class="modal-search-filters-form-btn">
          <%= submit_tag "Transmettre", id: "submit_btn" %>  
        </div>
                    
        </div>
            
      <%end%>
  </div>
</div>

<script>
  $('.document-check').hide();
  $('.document-type').hide();
    function readURL(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();
          reader.onload = function(e) {
         
              
          }
          reader.readAsDataURL(input.files[0]);
      }
  }
  $("input").change(function() {
      readURL(this);
      $('.document-check').show();
      $('.input-text').html($(this).val().replace(/C:\\fakepath\\/i, ''));
      $('.document-type').show();
  });

</script>

app/views/solideo_financements/new_financeur.html.erb
<div class="page_w">
  <div class="i24"></div>
  <div class="titre_page text-center">Ajouter un nouveau document</div>
  <div class="i40"></div>

     <div class="ED_new_form_box">
      <%= form_tag import_financeur_solideo_financements_path, multipart: true do%>
        <div class="document-file-input">
          <label><%= file_field_tag  :file, accept: '.xlsx' %>
            <div class="document-type"><i class="far fa-file-pdf"></i> </div>
            <div class="input-text"><i class="fas fa-plus-circle"></i><br>Ajouter un document</div>
            <div class="document-check">
            <i class="fas fa-check-circle"></i>
          </div>
          </label>
          
        <div class="modal-search-filters-form-btn">
          <%= submit_tag "Transmettre", id: "submit_btn" %>  
        </div>
                    
        </div>
        <% end %>
  </div>

</div>
<script>
  $('.document-check').hide();
  $('.document-type').hide();
    function readURL(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();
          reader.onload = function(e) {
         
              
          }
          reader.readAsDataURL(input.files[0]);
      }
  }
  $("input").change(function() {
      readURL(this);
      $('.document-check').show();
      $('.input-text').html($(this).val().replace(/C:\\fakepath\\/i, ''));
      $('.document-type').show();
  });

</script>