config/routes.rb
Rails.application.routes.draw do
  
  resources :innovations
  resources :chorus do 
    collection do 
      post 'import' => 'chorus#import'
     
    end
  end 
 
  devise_for :users, :path => "",
    :path_names =>  {:sign_in => "connexion", :sign_out => "deconnexion"}
  ActiveAdmin.routes(self)
  resources :ouvrages_financements do 
    collection {post :import}
  end
  resources :ouvrages_depenses do 
    collection do 
      post 'import' => 'ouvrages_depenses#import'
    end
  end 
  resources :solideo_depenses do 
    collection do 
      post 'import_structure' => 'solideo_depenses#import_structure'
      post 'import_depenses' => 'solideo_depenses#import_depenses'
    end 
  end
  resources :solideo_financements do 
    collection do 
      post 'import' => 'solideo_financements#import'
      post 'import2' => 'solideo_financements#import2'
      post 'deleteall' => 'solideo_financements#delete_financements'
      post 'import_financeur' => 'solideo_financements#import_financeur'
      post 'import_financements' => 'solideo_financements#import_financements'
    end 
    
  end 

  resources :etat_budgets
  resources :etat_depenses do 
    collection do 
      post 'import' => 'etat_depenses#import'
    end 
  end
  resources :ouvrages do 
    collection {post :import}
  end 
  resources :documents

  resources :innovations do 
    collection do 
      post 'import' => 'innovations#import'
      post 'import2' => 'innovations#import2'
      post 'import_categorie' => 'innovations#import_categorie'
    end 
  end
  get '/new-versement'=>'innovations#new_versement'
  get '/new-categorie'=>'innovations#new_categorie'
  root 'pages#home'
  
  get 'documents-solideo' => 'documents#documents_solideo'

  get 'new_structure' => 'solideo_depenses#new_structure'
  get 'new_financeur' => 'solideo_financements#new_financeur'
  
  get 'etat_depenses_filter' => 'etat_depenses#index_filter'
  get 'solideo_financements_filter' => 'solideo_financements#index_filter'
  
  
  get 'recherche-ouvrages' => 'ouvrages#search'
  get 'recherche-projets' => 'innovations#search'
  post 'delete-document' => 'documents#delete_file'
  
  get 'timeline' => 'ouvrages#timeline'
  get 'risques' => 'ouvrages#risques'
  post 'select_bop' => 'chorus#select_bop'
  post 'select_uo' => 'chorus#select_uo'
   post 'select_date_programme' => 'chorus#select_date_programme'
  post 'select_action' => 'chorus#select_action'
  get 'new_nom' => 'chorus#new_nom'
   post 'import_nom' => 'chorus#import_nom'
  get 'search_choru' => "chorus#search_choru"
  
  post 'import_maquette' => "ouvrages_depenses#import_maquette"

  
  post 'update_file' => 'ouvrages#update_file'
  get 'les-jop2024' => 'pages#jop2024'
  get 'synthese' => "pages#synthese"
  get 'reporting' => "pages#reporting"

  get 'mentions-legales' => "pages#mentions"
  get 'accessibilite' => "pages#accessibilite"
  get 'public' => "pages#public"
  get 'utilisation-budget' => 'pages#interets'
  get 'impacts' => 'pages#impacts'
  post 'maquette-date' => 'ouvrages_depenses#maquette_date'

  post 'form-edit' => 'innovations#form_edit'

  post 'import_disciplines' => "pages#import_disciplines"
  get 'new-disciplines' => "pages#new_disciplines"
  post 'import_ouvrages_publics' => "pages#import_ouvrages_publics"
  get 'new-ouvrages-publics' => "pages#new_ouvrages_publics"

  get 'recherche-ouvrages-publics' => 'pages#search_ouvrages_publics'

  post 'supp' => 'chorus#supp'
  post 'sort_table_programme' => "chorus#sort_table_programme"

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ouvrage.rb
class Ouvrage < ApplicationRecord

  has_many :ouvrages_financements, dependent: :destroy
  has_many :ouvrages_depenses, dependent: :destroy
  has_many :innovations, dependent: :destroy
  geocoded_by :adresse
  after_validation :geocode
  require 'csv'

  def self.import(file)
    CSV.foreach(file.path) do |row|
      #Ouvrage.create! row.to_hash
      if Ouvrage.find_by_name(row[0]).nil?
        @ouvrage = Ouvrage.new
      else
        @ouvrage = Ouvrage.find_by_name(row[0])
      end 
      @ouvrage.name = row[0]
      @ouvrage.adresse = row[1]
      @ouvrage.maitre_oeuvre = row[2]
      @ouvrage.budget = row[3]
      if !@ouvrage.budget.nil?
        @ouvrage.budget = @ouvrage.budget * 1000
      else 
        @ouvrage.budget = 0
      end
      @ouvrage.description = row[4]
      @ouvrage.heritage = row[5]
      @ouvrage.start = row[6]
      @ouvrage.end = row[7]
      @ouvrage.save
    end

  end
  def self.update_file(file)
    CSV.foreach(file.path) do |row|
      #Ouvrage.create! row.to_hash
     
      @ouvrage = Ouvrage.find_by_name(row[0])
      if !@ouvrage.nil?
       # @ouvrage.maitre_oeuvre = row[1]
        @ouvrage.budget = row[2]
        if !@ouvrage.budget.nil?
          @ouvrage.budget = @ouvrage.budget * 1000
        else 
          @ouvrage.budget = 0
        end
       # @ouvrage.adresse = row[3]
        @ouvrage.save
      end
    end
  end
  
    has_one_attached :photo, dependent: :destroy
end

app/controllers/ouvrages_controller.rb
class OuvragesController < ApplicationController
  before_action :set_ouvrage, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  require 'csv'
  # GET /ouvrages
  # GET /ouvrages.json
  def index
     @nav=true
    @q = Ouvrage.all.ransack(params[:q])
   
    @ouvrages = Ouvrage.all

    @maitre_oeuvre = []
    @maitre_oeuvre_all = []
    @array= []
    @ouvrages.all.each do |ouvrage|
      if ouvrage.maitre_oeuvre != "SOLIDEO"
      @maitre_oeuvre << ouvrage.maitre_oeuvre
      end
      @maitre_oeuvre_all << ouvrage.maitre_oeuvre
      @array << ouvrage.name
    end
    @maitre_oeuvre.uniq!
    @maitre_oeuvre_all.uniq!

    if params[:term]
        @ouvrages = Ouvrage.where('name like ?', "%#{params[:term]}%")
        
        render json: @ouvrages.map(&:name)  
      end
    
  
    @list_structure_ouvrages = SolideoStructure.where('categorie = ? OR categorie = ? ',"OUVRAGE HORS MOA SOLIDEO", "OUVRAGE MOA SOLIDEO").pluck(:id)
    @etat_id = SolideoFinanceur.where('name = ? ',"Etat").first.id 
    @collectivites = SolideoFinanceur.where('categorie = ? AND name != ?','SUBVENTION', "Etat").pluck(:id)
          
  end
  
  def search 
    @ouvrages = Ouvrage.all
    @q = @ouvrages.ransack(params[:q])
    @ouvrages = @q.result
    
    @maitre_oeuvre = []
    @maitre_oeuvre_all = []
    @array= []
    @ouvrages.all.each do |ouvrage|
      if ouvrage.maitre_oeuvre != "SOLIDEO"
      @maitre_oeuvre << ouvrage.maitre_oeuvre
      end
      @maitre_oeuvre_all << ouvrage.maitre_oeuvre
      @array << ouvrage.name
    end
    @maitre_oeuvre.uniq!
    @maitre_oeuvre_all.uniq!
    
    respond_to do |format|

     format.js

    end
  end 

  # GET /ouvrages/1
  # GET /ouvrages/1.json
  def show
    @navshow = true 
    @nav=true
    @ouvrage_depenses = OuvragesDepense.all.where('ouvrage_id = ?', @ouvrage.id)

   
  end

  # GET /ouvrages/new
  def new
    @ouvrage = Ouvrage.new
  end

  # GET /ouvrages/1/edit
  def edit
  end


  def import
    Ouvrage.import(params[:file])
    redirect_to ouvrages_path
    
  end 
  def update_file
    Ouvrage.update_file(params[:file])
    redirect_to ouvrages_path
  end 
  
  # POST /ouvrages
  # POST /ouvrages.json
  def create 
    @ouvrage = Ouvrage.new(ouvrage_params)

    respond_to do |format|
      if @ouvrage.save
        format.html { redirect_to @ouvrage, notice: 'Ouvrage was successfully created.' }
        format.json { render :show, status: :created, location: @ouvrage }
      else
        format.html { render :new }
        format.json { render json: @ouvrage.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # PATCH/PUT /ouvrages/1
  # PATCH/PUT /ouvrages/1.json
  def update
    respond_to do |format|
      if @ouvrage.update(ouvrage_params)
        format.html { redirect_to @ouvrage, notice: 'Ouvrage was successfully updated.' }
        format.json { render :show, status: :ok, location: @ouvrage }
      else
        format.html { render :edit }
        format.json { render json: @ouvrage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ouvrages/1
  # DELETE /ouvrages/1.json
  def destroy
    @ouvrage = Ouvrage.find(params[:id])
    @ouvrage.destroy
    respond_to do |format|
      format.html { redirect_to ouvrages_url, notice: 'Ouvrage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def timeline
    @nav=true 
  end 

  def risques
    @nav=true 
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ouvrage
      @ouvrage = Ouvrage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ouvrage_params
      params.require(:ouvrage).permit(:name, :adresse, :maitre_oeuvre, :budget ,:photo, :description, :phase_jo, :heritage, :start, :end, :date)
    end
end

app/helpers/ouvrages_helper.rb
module OuvragesHelper
end

app/views/ouvrages/_form.html.erb
<div class="ED_new_form_box">
<%= form_with(model: ouvrage, local: true) do |form| %>
  <% if ouvrage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ouvrage.errors.count, "error") %> prohibited this ouvrage from being saved:</h2>

      <ul>
      <% ouvrage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="ED_new_form_field">
    <%= form.label :name, "Nom de l'ouvrage" %>
    <%= form.text_field :name, required: true  %>
  </div>
  <div class="ED_new_form_field">
    <%= form.label :maitre_oeuvre, "MO de l'ouvrage" %>
    <%= form.text_field :maitre_oeuvre, required: true  %>
  </div>
  <div class="ED_new_form_field ED_new_form_field_date">
    <%= form.label :date %>
    <%= form.date_select :date, {:order => [:year]}, class: "ED_new_form_input_date"  %>
  </div>
  <div class="ED_new_form_field">
    <%= form.label :budget, "budget de l'ouvrage" %>
    <%= form.number_field :budget, min: 0, required: true  %>
  </div>
  <div class="ED_new_form_field">
    <%= form.label :adresse, "Adresse de l'ouvrage" %>
      </div>
  <div class="ED_new_form_field2">
    <%= form.text_field :adresse, id: "user_input_autocomplete_address", required: true  %>
  </div>
  <div class="ED_new_form_field">
    <%= form.label :description%>
    </div>
  <div class="ED_new_form_field2">
    <%= form.text_field :description, required: true %>
  </div>
  <div class="ED_new_form_field">
    <%= form.label :phase_jo %>
    </div>
  <div class="ED_new_form_field2">
    <%= form.text_field :phase_jo, required: true  %>
  </div>
  <div class="ED_new_form_field">
    <%= form.label :heritage %>
  </div>
  <div class="ED_new_form_field2">
    <%= form.text_field :heritage, required: true  %>
  </div>
  <div class="ED_new_form_field">
    <%= form.label :start, "Début des travaux"%>
  </div>
  <div class="ED_new_form_field2">
    <%= form.date_select :start,discard_day: true,  class: "ED_new_form_input_date"  %>
  </div>
  <div class="ED_new_form_field">
    <%= form.label :end, "fin des travaux"%>
      </div>
  <div class="ED_new_form_field2">
    <%= form.date_select :end,discard_day: true,  class: "ED_new_form_input_date"  %>
  </div>

  <div class="ED_new_form_field">
    <%= form.label :photo, "Photo de l'ouvrage" %>
    <%= form.file_field :photo %>
  </div>

  <div class="ED_new_form_field_submit">
    <%= form.submit 'Valider '%>
  </div>
<% end %>
</div>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCzB6sn07VIK_DzRsbm87THvZtEO1qPaNg&libraries=places"></script>


<script type="text/javascript">
var input = document.getElementById('user_input_autocomplete_address');
var options = {
  types: ['geocode'],
  componentRestrictions: {country: 'fr'}
};

autocomplete = new google.maps.places.Autocomplete(input, options);
  

</script>

app/views/ouvrages/_liste.html.erb
<div class="row">
  <div class="col-md-6">
  
       <%= search_form_for @q, url: recherche_ouvrages_path , method: :get, remote: true, id: "search-form" do |f| %>
        <div class="ouvrages-search">
           <%= f.search_field :name_cont,class: "ouvrages-search-field", id:"name",placeholder: "Rechercher un ouvrage", data: {autocomplete_source: ouvrages_path} %> 
          <%= f.button :submit, id:"submit_button", class:"ouvrages-submit" do %><i class="fas fa-search"></i><% end %>
        </div>
          <% end %>     
    
    <div class="ouvrages-box">
      <% if !@ouvrages.nil?%>
       <% if @ouvrages.where('maitre_oeuvre = ?', "SOLIDEO").count > 0 %>
         <div class='titre_tableau'>
           MOA : Solideo
         </div>
         <div class="i12"></div>
         <% @ouvrages.where('maitre_oeuvre = ?', "SOLIDEO").where.not('name like ?',"%SITE d'ENTRAINEMENT%").each do |ouvrage| %>
          <div class="O-name">
            <%= link_to ouvrage do %>
              <%= ouvrage.name %>  
              <% if Maquette.where('ouvrage_id =?',ouvrage.id).order('date DESC').count > 0 %><span>- <%= number_with_delimiter((Maquette.where('ouvrage_id =?',ouvrage.id).order('date DESC').first.total/1000).to_i, :delimiter => ' ')%> k€</span> <% end %>    
            <% end %>
          </div>
          <% end %>
          <% @ouvrages.where('maitre_oeuvre = ?', "SOLIDEO").where('name like ?',"%SITE d'ENTRAINEMENT%").each do |ouvrage| %>
          <div class="O-name">
            <%= link_to ouvrage do %>
              <%= ouvrage.name %>  
              <% if Maquette.where('ouvrage_id =?',ouvrage.id).order('date DESC').count > 0 %>
              <span>- <%= number_with_delimiter((Maquette.where('ouvrage_id =?',ouvrage.id).order('date DESC').first.total/1000).to_i, :delimiter => ' ')%> k€</span>  
              <% end %>      
            <% end %>
          </div>
          <% end %>
        <% end %>
        <br><br>
       <% @maitre_oeuvre.each do |mo|%>
         <div class='titre_tableau'>
           MOA : <%= mo %>
         </div>
         <div class="i12"></div>
         <% @ouvrages.where('maitre_oeuvre = ?', mo).where.not('name like ?',"%SITE d'ENTRAINEMENT%").each do |ouvrage| %>
          <div class="O-name">
          <%= link_to ouvrage do %>
            <%= ouvrage.name %>  
            <% if Maquette.where('ouvrage_id =?',ouvrage.id).order('date DESC').count > 0 %><span>- <%= number_with_delimiter((Maquette.where('ouvrage_id =?',ouvrage.id).order('date DESC').first.total/1000).to_i, :delimiter => ' ')%> k€</span>   
            <% end %>     
          <% end %>
          </div>
         <% end %>
         
       
         <% @ouvrages.where('maitre_oeuvre = ?', mo).where('name like ?',"%SITE d'ENTRAINEMENT%").each do |ouvrage| %>
          <div class="O-name">
          <%= link_to ouvrage do %>
            <%= ouvrage.name %>  
            <% if Maquette.where('ouvrage_id =?',ouvrage.id).order('date DESC').count > 0 %>
            <span>- <%= number_with_delimiter((Maquette.where('ouvrage_id =?',ouvrage.id).order('date DESC').first.total/1000).to_i, :delimiter => ' ')%> k€</span>  
            <% end %>      
          <% end %>
          </div>
         <% end %>
      
       <br>
       <% end %>
       
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
      <div id="map">
      
      </div>

    </div>
</div>

 <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCzB6sn07VIK_DzRsbm87THvZtEO1qPaNg&map_ids=4c4b12db708d00c6&callback=initMap"
      defer
    ></script>
<script>

function initMap() {
  var map = new google.maps.Map(document.getElementById("map"), {
    mapId: "4c4b12db708d00c6",
    center: { lat: <%= @ouvrages.first.latitude%>, lng: <%= @ouvrages.first.longitude%> },
    zoom: 10,
    
  });

  var infowindow = new google.maps.InfoWindow({
                         content:''
                       });
              var image = {
                          path: 'M0-48c-9.8 0-17.7 7.8-17.7 17.4 0 15.5 17.7 30.6 17.7 30.6s17.7-15.4 17.7-30.6c0-9.6-7.9-17.4-17.7-17.4z',
                          fillColor: '#000091',
                          fillOpacity: 1,
                          scale: 0.5,
                          strokeColor: '#000091',
                          strokeWeight: 1,
                          labelOrigin: new google.maps.Point(0, -30)
                        };
              var image2 ={
                          path: 'M0-48c-9.8 0-17.7 7.8-17.7 17.4 0 15.5 17.7 30.6 17.7 30.6s17.7-15.4 17.7-30.6c0-9.6-7.9-17.4-17.7-17.4z',
                          fillColor: '#000091',
                          fillOpacity: 1,
                          scale: 0.6,
                          strokeColor: '#000091',
                          strokeWeight: 1,
                          labelOrigin: new google.maps.Point(0, -30)
                        };
              var imager = {
                          path: 'M0-48c-9.8 0-17.7 7.8-17.7 17.4 0 15.5 17.7 30.6 17.7 30.6s17.7-15.4 17.7-30.6c0-9.6-7.9-17.4-17.7-17.4z',
                          fillColor: '#F1013B',
                          fillOpacity: 1,
                          scale: 0.5,
                          strokeColor: '#F1013B',
                          strokeWeight: 1,
                          labelOrigin: new google.maps.Point(0, -30)
                        };
            var image2r ={
                          path: 'M0-48c-9.8 0-17.7 7.8-17.7 17.4 0 15.5 17.7 30.6 17.7 30.6s17.7-15.4 17.7-30.6c0-9.6-7.9-17.4-17.7-17.4z',
                          fillColor: '#F1013B',
                          fillOpacity: 1,
                          scale: 0.6,
                          strokeColor: '#F1013B',
                          strokeWeight: 1,
                          labelOrigin: new google.maps.Point(0, -30)
                        };
  var imagei = {
                          path: 'M0-48c-9.8 0-17.7 7.8-17.7 17.4 0 15.5 17.7 30.6 17.7 30.6s17.7-15.4 17.7-30.6c0-9.6-7.9-17.4-17.7-17.4z',
                          fillColor: '#FD9C04',
                          fillOpacity: 1,
                          scale: 0.5,
                          strokeColor: '#FD9C04',
                          strokeWeight: 1,
                          labelOrigin: new google.maps.Point(0, -30)
                        };
            var image2i ={
                          path: 'M0-48c-9.8 0-17.7 7.8-17.7 17.4 0 15.5 17.7 30.6 17.7 30.6s17.7-15.4 17.7-30.6c0-9.6-7.9-17.4-17.7-17.4z',
                          fillColor: '#FD9C04',
                          fillOpacity: 1,
                          scale: 0.6,
                          strokeColor: '#FD9C04',
                          strokeWeight: 1,
                          labelOrigin: new google.maps.Point(0, -30)
                        };
  
  
        <% @ouvrages.each do |ouvrage| %>
                        
                var marker = new google.maps.Marker({
                                position: {lat: <% if ouvrage.latitude.nil?%>48.856614<% else%><%= ouvrage.latitude%><%end%>, lng: <% if ouvrage.longitude.nil?%>2.3522219<% else %><%= ouvrage.longitude%><%end%>},
                                map: map,
                                icon: image ,
                                label: {
                                     fontFamily: "'Font Awesome 5 Free'",
                                      text: '\uf6e3', //icon code
                                      fontWeight: '900', //careful! some icons in FA5 only exist for specific font weights
                                      color: '#FFFFFF', //color of the text inside marker
                                      fontSize: '8px'
                                },
                              });
                
                      
                          
                bindInfoWindow(marker, map, infowindow, '<div class="search-container-fluid">'+ '<p class="search-name"><%= link_to ouvrage_path(ouvrage) do %><%= ouvrage.name%><% end %></p>'+ '</div>');
       
                               
                                AddMouseover(marker, image, image2);
                             
                      
                <% end %>
                }
                      
                function bindInfoWindow(marker, map, infowindow, html) {   
                   
                        google.maps.event.addListener(marker,'click', function() {
                              infowindow.setContent(html); 
                              infowindow.open(map, marker);
                            });
                       google.maps.event.addListener(infowindow, 'domready', function() {
                       // Reference to the DIV which receives the contents of the infowindow using jQuery
                       var iwOuter = $('.gm-style-iw');
                       var iwBackground = iwOuter.prev();
                       // Remove the background shadow DIV
                       iwBackground.children(':nth-child(2)').css({'display' : 'none'});
                       // Remove the white background DIV
                       iwBackground.children(':nth-child(4)').css({'display' : 'none'});
                       // iwOuter.children().css({'width':'100%'})
                       //iwOuter.parent().parent().css({left: '20px'});
                                      // Moves the shadow of the arrow 76px to the left margin 
                       // iwBackground.children(':nth-child(1)').attr('style', function(i,s){ return s + 'right: 20px !important;'});
                        // Moves the arrow 76px to the left margin 
                       // iwBackground.children(':nth-child(3)').attr('style', function(i,s){ return s + 'right: 20px !important;'});
                                      // Changes the desired color for the tail outline.
                        // The outline of the tail is composed of two descendants of div which contains the tail.
                        // The .find('div').children() method refers to all the div which are direct descendants of the previous div. 
                        iwBackground.children(':nth-child(3)').find('div').children().css({'box-shadow': 'rgba(130,153,247,0.2) 0px 1px 6px', 'z-index' : '1'});
                        var iwCloseBtn = iwOuter.next();
                        // Apply the desired effect to the close button
                        iwCloseBtn.css({
                          opacity: '1', // by default the close button has an opacity of 0.7
                          right: '20px', top: '3px', // button repositioning
                          color: '#3233FF',
                          //border: '1px solid transparent', // increasing button border and new color
                          //'border-radius': '13px', // circular effect
                          //'box-shadow': '0 0 5px #fff' // 3D effect to highlight the button
                          });
                        // The API automatically applies 0.7 opacity to the button after the mouseout event.
                        // This function reverses this event to the desired value.
                        iwCloseBtn.mouseout(function(){
                          $(this).css({opacity: '1'});
                        })
                      });
                    }
                function AddMouseover(marker, image, image2){
                        google.maps.event.addListener(marker,'mouseover', function() {
                              marker.setIcon(image2);
                              var label = this.getLabel();
                                label.color="white";
                              this.setLabel(label)
                            });
                        google.maps.event.addListener(marker,'mouseout', function() {
                              marker.setIcon(image);
                              var label = this.getLabel();
                                label.color="white";
                              this.setLabel(label)
                            });
                      
                }
                     
                      
</script>
<script>

  $(function() {
 // var matieres = ["Stade de france", "Arena 2", "village"]
  // Below is the name of the textfield that will be autocomplete    
    $('#name').autocomplete({
 // This is the source of the auocomplete suggestions. In this case a list of names from the people controller, in JSON format.
     
      source: $('#name').data('autocomplete-source'),
          //  source:matieres,
           
      select: function(event, ui) {
       // $.ajax({
       //   type:'GET',
       //   url: '/ouvrages',
          
        //});
        $("#name").val(ui.item.label);
          $("#submit_button").click()    

    },
        })
     .data("ui-autocomplete")._renderItem = function(ul, item){
       var expression = new RegExp(this.term, "gi");
      var result = expression.exec(item.label);
      var answer; 
      if (result.index == 0){
        answer = item.label.replace(expression, "<span style='font-weight:bold;color:#000091'>" + this.term + "</span>");
        return $("<li></li>")
      .append("<a>"+answer+"</a>")
      .prependTo(ul);
      }   
      else
       answer = item.label.replace(expression, "<span style='font-weight:bold;color:#000091'>" + this.term.toLowerCase() + "</span>");
      return $("<li></li>")
      .append("<a>"+answer+"</a>")
      .appendTo(ul);
     
    };
    
  });
</script>

app/views/ouvrages/edit.html.erb
<div class="page_w">
  <div class="i24"></div>
  <div>
    <%= link_to @ouvrage, class:"bouton" do %><i class="fas fa-chevron-left"></i>Retour<%end %>
  </div>
  <div class="titre_page text-center">Modifier l'ouvrage</div>
  <div class="i40"></div>
  <%= render 'form', ouvrage: @ouvrage %>

  <div class="i40"></div>
  <div>
    <%= link_to ouvrage_path,class:"bouton", method: :delete do %>supprimer l'ouvrage <% end %>
  </div>

</div>

app/views/ouvrages/new.html.erb
<div class="page_w">
  <div class="i24"></div>
  <div>
    <%= link_to ouvrages_path, class: 'bouton' do %><i class="fas fa-chevron-left"></i>Retour<%end %>
  </div>
  <div class="titre_page text-center">Ajouter des ouvrages</div>
  <div class="i40"></div>
  <div class="ED_new_form_box">
  <%=form_tag import_ouvrages_path, multipart: true do %>
    
    <div class="document-file-input">
          <label><%= file_field_tag :file, accept: '.csv'  %>
            <div class="document-type"><i class="far fa-file-pdf"></i> </div>
            <div class="input-text"><i class="fas fa-plus-circle"></i><br>Ajouter un document</div>
            <div class="document-check">
            <i class="fas fa-check-circle"></i>
          </div>
          </label>
          
        <div class="modal-search-filters-form-btn">
          <%= submit_tag "Transmettre", id: "submit_btn" %>  
        </div>
                    
    </div>

  <%end%>
</div>

 <div class="i40"></div>

</div>

<script>
  $('.document-check').hide();
  $('.document-type').hide();
    function readURL(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();
          reader.onload = function(e) {
         
              
          }
          reader.readAsDataURL(input.files[0]);
      }
  }
  $("input").change(function() {
      readURL(this);
      $('.document-check').show();
      $('.input-text').html($(this).val().replace(/C:\\fakepath\\/i, ''));
      $('.document-type').show();
  });

</script>

app/views/ouvrages/search.js.erb
$('#ouvrages-results').html("<%=j render 'ouvrages/liste' %>")