config/routes.rb
Rails.application.routes.draw do
  
  resources :innovations
  resources :chorus do 
    collection do 
      post 'import' => 'chorus#import'
     
    end
  end 
 
  devise_for :users, :path => "",
    :path_names =>  {:sign_in => "connexion", :sign_out => "deconnexion"}
  ActiveAdmin.routes(self)
  resources :ouvrages_financements do 
    collection {post :import}
  end
  resources :ouvrages_depenses do 
    collection do 
      post 'import' => 'ouvrages_depenses#import'
    end
  end 
  resources :solideo_depenses do 
    collection do 
      post 'import_structure' => 'solideo_depenses#import_structure'
      post 'import_depenses' => 'solideo_depenses#import_depenses'
    end 
  end
  resources :solideo_financements do 
    collection do 
      post 'import' => 'solideo_financements#import'
      post 'import2' => 'solideo_financements#import2'
      post 'deleteall' => 'solideo_financements#delete_financements'
      post 'import_financeur' => 'solideo_financements#import_financeur'
      post 'import_financements' => 'solideo_financements#import_financements'
    end 
    
  end 

  resources :etat_budgets
  resources :etat_depenses do 
    collection do 
      post 'import' => 'etat_depenses#import'
    end 
  end
  resources :ouvrages do 
    collection {post :import}
  end 
  resources :documents

  resources :innovations do 
    collection do 
      post 'import' => 'innovations#import'
      post 'import2' => 'innovations#import2'
      post 'import_categorie' => 'innovations#import_categorie'
    end 
  end
  get '/new-versement'=>'innovations#new_versement'
  get '/new-categorie'=>'innovations#new_categorie'
  root 'pages#home'
  
  get 'documents-solideo' => 'documents#documents_solideo'

  get 'new_structure' => 'solideo_depenses#new_structure'
  get 'new_financeur' => 'solideo_financements#new_financeur'
  
  get 'etat_depenses_filter' => 'etat_depenses#index_filter'
  get 'solideo_financements_filter' => 'solideo_financements#index_filter'
  
  
  get 'recherche-ouvrages' => 'ouvrages#search'
  get 'recherche-projets' => 'innovations#search'
  post 'delete-document' => 'documents#delete_file'
  
  get 'timeline' => 'ouvrages#timeline'
  get 'risques' => 'ouvrages#risques'
  post 'select_bop' => 'chorus#select_bop'
  post 'select_uo' => 'chorus#select_uo'
   post 'select_date_programme' => 'chorus#select_date_programme'
  post 'select_action' => 'chorus#select_action'
  get 'new_nom' => 'chorus#new_nom'
   post 'import_nom' => 'chorus#import_nom'
  get 'search_choru' => "chorus#search_choru"
  
  post 'import_maquette' => "ouvrages_depenses#import_maquette"

  
  post 'update_file' => 'ouvrages#update_file'
  get 'les-jop2024' => 'pages#jop2024'
  get 'synthese' => "pages#synthese"
  get 'reporting' => "pages#reporting"

  get 'mentions-legales' => "pages#mentions"
  get 'accessibilite' => "pages#accessibilite"
  get 'public' => "pages#public"
  get 'utilisation-budget' => 'pages#interets'
  get 'impacts' => 'pages#impacts'
  post 'maquette-date' => 'ouvrages_depenses#maquette_date'

  post 'form-edit' => 'innovations#form_edit'

  post 'import_disciplines' => "pages#import_disciplines"
  get 'new-disciplines' => "pages#new_disciplines"
  post 'import_ouvrages_publics' => "pages#import_ouvrages_publics"
  get 'new-ouvrages-publics' => "pages#new_ouvrages_publics"

  get 'recherche-ouvrages-publics' => 'pages#search_ouvrages_publics'

  post 'supp' => 'chorus#supp'
  post 'sort_table_programme' => "chorus#sort_table_programme"

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ouvrages_financement.rb
class OuvragesFinancement < ApplicationRecord
  belongs_to :ouvrage
  
   require 'csv'

  def self.import_ouvrage(file, date_year, date_month)
    @financeurs = ["","privé", "Etat", "RIF", "Ville de Paris", "Métropole Grand Paris", "CD92", "CD93", "CD78", "EPT Plaine Commune","EPT Terres d'envol", "Ville de Dugny", "Ville du Bourget", "CASQY", "Ville de Marseille"]

    CSV.foreach(file.path) do |row|
      if !row[0].nil? && !row[0].empty?
        @ouvrage = Ouvrage.find_by_name(row[0])
        if !@ouvrage.nil?
          1.upto(14).each do |i|
            if !row[i].nil? 
              @ouvrage_financement = @ouvrage.ouvrages_financements.new
              @ouvrage_financement.montant = row[i]
              @ouvrage_financement.montant = @ouvrage_financement.montant * 1000
              @ouvrage_financement.montant_prevu = row[15]
              @ouvrage_financement.montant_prevu = @ouvrage_financement.montant_prevu * 1000
              @ouvrage_financement.name = @financeurs[i]
              @ouvrage_financement.date = Date.new(date_year, date_month)
              if @ouvrage_financement.montant.to_i != 0
              @ouvrage_financement.save
              end 
            end  
          end
        end
      end
    end
  end
  
    def self.import_ouvrage2(file, date_year, date_month)
    @financeurs = ["","privé", "Etat", "RIF", "Ville de Paris", "Métropole Grand Paris", "CD92", "CD93", "CD78", "EPT Plaine Commune","EPT Terres d'envol", "Ville de Dugny", "Ville du Bourget", "CASQY", "Ville de Marseille"]

    CSV.foreach(file.path) do |row|
      if !row[0].nil? || !row[0].empty?
        @ouvrage = Ouvrage.find_by_name(row[0])
        if !@ouvrage.nil?
          1.upto(14).each do |i|
            if !row[i].nil? 
              @ouvrage_financement = @ouvrage.ouvrages_financements.where('name = ? AND date = ?', @financeurs[i], Date.new(date_year, date_month)).first
              if !@ouvrage_financement.nil?
                @ouvrage_financement.montant = row[i]
                @ouvrage_financement.montant = @ouvrage_financement.montant * 1000

                if @ouvrage_financement.montant.to_i != 0
                @ouvrage_financement.save
                end 
              else
                @ouvrage_financement = @ouvrage.ouvrages_financements.new
                @ouvrage_financement.montant_prevu = 0
                @ouvrage_financement.name = @financeurs[i]
                @ouvrage_financement.date = DateTime.new(date_year, date_month)
                @ouvrage_financement.montant = row[i]
                @ouvrage_financement.montant = @ouvrage_financement.montant * 1000
                
                if @ouvrage_financement.montant.to_i != 0
                  @ouvrage_financement.save
                end 
                
              end
            end  
          end
        end
      end
    end
  end
end

app/controllers/ouvrages_financements_controller.rb
class OuvragesFinancementsController < ApplicationController
  before_action :set_ouvrages_financement, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!
  # GET /ouvrages_financements
  # GET /ouvrages_financements.json
  def index
     @nav=true
    @ouvrages_financements = OuvragesFinancement.all
  end

  # GET /ouvrages_financements/1
  # GET /ouvrages_financements/1.json
  def show
  end

  # GET /ouvrages_financements/new
  def new
    @ouvrages_financement = OuvragesFinancement.new
  end

  # GET /ouvrages_financements/1/edit
  def edit
  end
  
  def import
    @ouvrages_financements = OuvragesFinancement.import_ouvrage(params[:file], params[:date_year].to_i, params[:date_month].to_i)
    redirect_to ouvrages_financements_path
  end

  # POST /ouvrages_financements
  # POST /ouvrages_financements.json
  def create
    @ouvrages_financement = OuvragesFinancement.new(ouvrages_financement_params)

    respond_to do |format|
      if @ouvrages_financement.save
        format.html { redirect_to ouvrages_financements_path, notice: 'Ouvrages financement was successfully created.' }
        format.json { render :show, status: :created, location: @ouvrages_financement }
      else
        format.html { render :new }
        format.json { render json: @ouvrages_financement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ouvrages_financements/1
  # PATCH/PUT /ouvrages_financements/1.json
  def update
    respond_to do |format|
      if @ouvrages_financement.update(ouvrages_financement_params)
        format.html { redirect_to ouvrages_financements_path, notice: 'Ouvrages financement was successfully updated.' }
        format.json { render :show, status: :ok, location: @ouvrages_financement }
      else
        format.html { render :edit }
        format.json { render json: @ouvrages_financement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ouvrages_financements/1
  # DELETE /ouvrages_financements/1.json
  def destroy
    @ouvrages_financement.destroy
    respond_to do |format|
      format.html { redirect_to ouvrages_financements_url, notice: 'Ouvrages financement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ouvrages_financement
      @ouvrages_financement = OuvragesFinancement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ouvrages_financement_params
      params.require(:ouvrages_financement).permit(:date, :ouvrage_id, :name, :montant)
    end
end

app/helpers/ouvrages_financements_helper.rb
module OuvragesFinancementsHelper
end

app/views/ouvrages_financements/_form.html.erb
<div class="ED_new_form_box">
<%= form_with(model: ouvrages_financement, local: true) do |form| %>
  <% if ouvrages_financement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ouvrages_financement.errors.count, "error") %> prohibited this ouvrages_financement from being saved:</h2>

      <ul>
      <% ouvrages_financement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="ED_new_form_field">
    <%= form.label :date %>
    <%= form.date_select :date, {:order => [:year]} %>
  </div>

  <div class="ED_new_form_field">
    <%= form.label :ouvrage_id %>
    <%= form.text_field :ouvrage_id %>
  </div>

  <div class="ED_new_form_field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="ED_new_form_field">
    <%= form.label :montant %>
    <%= form.text_field :montant %>
  </div>

  <div class="ED_new_form_field_submit">
    <%= form.submit 'Ajouter'%>
  </div>
<% end %>
</div>

app/views/ouvrages_financements/edit.html.erb
<h1>Editing Ouvrages Financement</h1>

<%= render 'form', ouvrages_financement: @ouvrages_financement %>

<%= link_to 'Show', @ouvrages_financement %> |
<%= link_to 'Back', ouvrages_financements_path %>

app/views/ouvrages_financements/index.html.erb
<h1>Ouvrages Financements</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Ouvrage</th>
      <th>Name</th>
      <th>Montant</th>
      <th>Montant prévu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ouvrages_financements.each do |ouvrages_financement| %>
      <tr>
        <td><%= ouvrages_financement.date %></td>
        <td><%= ouvrages_financement.ouvrage.name %></td>
        <td><%= ouvrages_financement.name %></td>
        <td><%= ouvrages_financement.montant %></td>
        <td><%= ouvrages_financement.montant_prevu %></td>
        <td><%= link_to 'Show', ouvrages_financement %></td>
        <td><%= link_to 'Edit', edit_ouvrages_financement_path(ouvrages_financement) %></td>
        <td><%= link_to 'Destroy', ouvrages_financement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ouvrages Financement', new_ouvrages_financement_path %>

app/views/ouvrages_financements/new.html.erb
<div class="page_w">
  <div class="i24"></div>
  <div class="titre_page text-center">Ajouter un nouveau document</div>
  <div class="i40"></div>


<%= render 'form', ouvrages_financement: @ouvrages_financement %>
</div>

app/views/ouvrages_financements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @ouvrages_financement.date %>
</p>

<p>
  <strong>Ouvrage:</strong>
  <%= @ouvrages_financement.ouvrage %>
</p>

<p>
  <strong>Name:</strong>
  <%= @ouvrages_financement.name %>
</p>

<p>
  <strong>Montant:</strong>
  <%= @ouvrages_financement.montant %>
</p>

<%= link_to 'Edit', edit_ouvrages_financement_path(@ouvrages_financement) %> |
<%= link_to 'Back', ouvrages_financements_path %>