config/routes.rb
Rails.application.routes.draw do
  
  resources :innovations
  resources :chorus do 
    collection do 
      post 'import' => 'chorus#import'
     
    end
  end 
 
  devise_for :users, :path => "",
    :path_names =>  {:sign_in => "connexion", :sign_out => "deconnexion"}
  ActiveAdmin.routes(self)
  resources :ouvrages_financements do 
    collection {post :import}
  end
  resources :ouvrages_depenses do 
    collection do 
      post 'import' => 'ouvrages_depenses#import'
    end
  end 
  resources :solideo_depenses do 
    collection do 
      post 'import_structure' => 'solideo_depenses#import_structure'
      post 'import_depenses' => 'solideo_depenses#import_depenses'
    end 
  end
  resources :solideo_financements do 
    collection do 
      post 'import' => 'solideo_financements#import'
      post 'import2' => 'solideo_financements#import2'
      post 'deleteall' => 'solideo_financements#delete_financements'
      post 'import_financeur' => 'solideo_financements#import_financeur'
      post 'import_financements' => 'solideo_financements#import_financements'
    end 
    
  end 

  resources :etat_budgets
  resources :etat_depenses do 
    collection do 
      post 'import' => 'etat_depenses#import'
    end 
  end
  resources :ouvrages do 
    collection {post :import}
  end 
  resources :documents

  resources :innovations do 
    collection do 
      post 'import' => 'innovations#import'
      post 'import2' => 'innovations#import2'
      post 'import_categorie' => 'innovations#import_categorie'
    end 
  end
  get '/new-versement'=>'innovations#new_versement'
  get '/new-categorie'=>'innovations#new_categorie'
  root 'pages#home'
  
  get 'documents-solideo' => 'documents#documents_solideo'

  get 'new_structure' => 'solideo_depenses#new_structure'
  get 'new_financeur' => 'solideo_financements#new_financeur'
  
  get 'etat_depenses_filter' => 'etat_depenses#index_filter'
  get 'solideo_financements_filter' => 'solideo_financements#index_filter'
  
  
  get 'recherche-ouvrages' => 'ouvrages#search'
  get 'recherche-projets' => 'innovations#search'
  post 'delete-document' => 'documents#delete_file'
  
  get 'timeline' => 'ouvrages#timeline'
  get 'risques' => 'ouvrages#risques'
  post 'select_bop' => 'chorus#select_bop'
  post 'select_uo' => 'chorus#select_uo'
   post 'select_date_programme' => 'chorus#select_date_programme'
  post 'select_action' => 'chorus#select_action'
  get 'new_nom' => 'chorus#new_nom'
   post 'import_nom' => 'chorus#import_nom'
  get 'search_choru' => "chorus#search_choru"
  
  post 'import_maquette' => "ouvrages_depenses#import_maquette"

  
  post 'update_file' => 'ouvrages#update_file'
  get 'les-jop2024' => 'pages#jop2024'
  get 'synthese' => "pages#synthese"
  get 'reporting' => "pages#reporting"

  get 'mentions-legales' => "pages#mentions"
  get 'accessibilite' => "pages#accessibilite"
  get 'public' => "pages#public"
  get 'utilisation-budget' => 'pages#interets'
  get 'impacts' => 'pages#impacts'
  post 'maquette-date' => 'ouvrages_depenses#maquette_date'

  post 'form-edit' => 'innovations#form_edit'

  post 'import_disciplines' => "pages#import_disciplines"
  get 'new-disciplines' => "pages#new_disciplines"
  post 'import_ouvrages_publics' => "pages#import_ouvrages_publics"
  get 'new-ouvrages-publics' => "pages#new_ouvrages_publics"

  get 'recherche-ouvrages-publics' => 'pages#search_ouvrages_publics'

  post 'supp' => 'chorus#supp'
  post 'sort_table_programme' => "chorus#sort_table_programme"

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/choru.rb
class Choru < ApplicationRecord
  require 'csv'
  
  def self.import(file)
    CSV.foreach(file.path) do |row|
      if !row[0].nil? && !row[0].empty?
        if (row[7].nil? || row[7].empty?)  #si ce nest pas des actions
         
            if Choru.where('compte_budgetaire = ? AND operation = ? AND type_piece = ? AND centre_financier = ? AND type_ae = ?' , row[5],row[2],row[1],row[4],row[8]).count > 0 && Choru.where('compte_budgetaire = ? AND operation = ? AND type_piece = ? AND centre_financier = ? AND type_ae = ?' , row[5],row[2],row[1], row[4], row[8]).order('date DESC').first.date > row[0].to_date - 7.days #on rassemble
                  @chorus = Choru.where('compte_budgetaire = ? AND operation = ? AND type_piece = ? AND centre_financier = ? AND type_ae = ?' , row[5],row[2],row[1],row[4],row[8]).order('date DESC').first
                  @chorus.montant = @chorus.montant + row[6].to_f/100 #cumul

                  if @chorus.montant == 0 
                   @chorus.destroy
                  end         
            else #count == 0 ou pas dans dernier jours 
              @chorus = Choru.new
              @chorus.date = row[0]
              @chorus.type_piece = row[1]
              @chorus.operation = row[2]
              @chorus.type_budget = row[3]
              @chorus.centre_financier = row[4]
              @chorus.compte_budgetaire = row[5]
              @chorus.montant = row[6].to_f/100
              @chorus.type_ae = row[8]   
            end 

            @chorus.save 
            if @chorus.date.nil?
              @chorus.destroy 
            end
        
        elsif (!row[7].nil? && !row[7].empty?) #c'est une action
          
          if Choru.where('compte_budgetaire = ? AND centre_financier = ? AND type_ae = ?', row[5],row[4], row[8]).where.not(domaine_fonctionnel: nil).count > 0 && Choru.where('compte_budgetaire = ? AND centre_financier = ? AND type_ae = ?' ,row[5],row[4], row[8]).where.not(domaine_fonctionnel: nil).order('date DESC').first.date > row[0].to_date - 7.days #on rassemble
                @chorus = Choru.where('compte_budgetaire = ? AND centre_financier = ? AND type_ae = ?' ,row[5],row[4],row[8]).where.not(domaine_fonctionnel: nil).order('date DESC').first
                @chorus.montant = @chorus.montant + row[6].to_f/100 #cumul
                if @chorus.montant == 0 
                  @chorus.destroy
                end              
          else #=0 ou pas dans les 7 derniers jours 5167 
            @chorus = Choru.new
            @chorus.date = row[0]
            @chorus.type_piece = row[1]
            @chorus.operation = row[2]
            @chorus.type_budget = row[3]
            @chorus.centre_financier = row[4]
            @chorus.compte_budgetaire = row[5]
            @chorus.montant = row[6].to_f/100
            @chorus.domaine_fonctionnel = 'action'
            @chorus.type_ae = row[8]
         
          end

          @chorus.save 
          if @chorus.date.nil?
            @chorus.destroy 
          end
       
        end 
      end
    end
  end

   def self.import_nom(file)
      CSV.foreach(file.path) do |row|
          if !row[0].nil? && !row[0].empty?
            @chorus_nom = ChorusNomenclature.new
            @chorus_nom.nom = row[0]
            @chorus_nom.designation = row[1]
            @chorus_nom.save
            
          end
      end
  end
  
end

app/controllers/chorus_controller.rb
class ChorusController < ApplicationController

  def index
    @q = Choru.all.ransack(params[:q])
    @chorus = Choru.all 
    @liste_programme = @chorus.select { |choru| choru.centre_financier.count("-") == 0 }
    @liste_programme = @liste_programme.map(&:centre_financier).uniq! 
    if params[:term]
       
        @chorus = Choru.where('centre_financier like ?', "%#{params[:term]}%")
        @chorus = @chorus.select { |choru| choru.centre_financier.count("-") == 0 }
         
        render json: @chorus.map(&:centre_financier).uniq!  
      end
  end 
  
  def new
    @choru = Choru.new
  end 
  def new_conso
  
  end 
  
  def import
   Choru.import(params[:file])
    redirect_to chorus_path 
  end
 
  def import_nom
    Choru.import_nom(params[:file])
    redirect_to chorus_path 
  end 
  
  def update 
  end 
  
  def search_choru
    if params[:q]
      @q = Choru.ransack(params[:q])
      #@results = @q.result
      @id = params[:q][:centre_financier_cont][0..2]
      redirect_to choru_path(:id => @id, :vision => params[:vision], :budget => params[:budget], :type_ae => params[:type_ae])
    end   
  end
  
  def select_date_programme
   
  end
  
  def show 
    @search = params[:id]
    @search2 = "0"+params[:id]
    @search3 = params[:id][1..3]
    @date = Date.new(2019,12,31)
    @dates = ['2020']
    
    if !Choru.where('centre_financier = ? ', @search2).first.nil?
      @search = @search2 #si on a avec 0 on prend celui la 
    elsif !Choru.where('centre_financier = ? ', @search3).first.nil?
      @search = @search3 #si on a avec 0 on prend celui la 
    end 
    if !Choru.where('centre_financier = ? ', @search).first.nil?
      if params[:vision]
      @vision = params[:vision]
      else
      @vision = '1'
      end
      if params[:budget]
      @budget = params[:budget]
      else
      @budget = 'HT2'
      end
       if params[:type_ae]
      @type_ae = params[:type_ae]
      else
      @type_ae = 'cp'
      end

      @chorus = Choru.where('type_ae = ? AND compte_budgetaire = ?',@type_ae, @budget).where('centre_financier like ? ', '%'+@search+'%') #tous les elements de ce programme
      
      if !@chorus.nil?
        @chorus = @chorus.order('date ASC')
        @programme = Choru.where('type_ae = ? AND centre_financier = ? AND date >= ? AND date <= ? AND compte_budgetaire = ?',@type_ae, @search, @date, @date + 1.year, @budget)

        if !@programme.nil? && @programme.count > 0
          @programme = @programme.order('date ASC,montant DESC')
          @type_pieces = @programme.pluck(:type_piece).uniq
          
          @montant_lfi = @programme.where('type_budget = ?', "Bud. voté ou en cours de vote").sum('montant').to_i
          @montant_dispo = @chorus.where(domaine_fonctionnel: nil).sum('montant').to_i
          @montant_reserve = @programme.where('type_piece = ?','RB').sum('montant').to_i
          if @budget == "T2"
            @montant_conso = Choru.where('centre_financier like ?','%'+@search+'%').where.not(domaine_fonctionnel: nil).where('date >= ? AND date <= ? AND type_ae = ? AND (compte_budgetaire = ? OR compte_budgetaire = ? OR compte_budgetaire = ?)', @date, @date + 1.year,@type_ae, "21","22","23").sum('montant').to_i
          else 
            @montant_conso = Choru.where('centre_financier like ?','%'+@search+'%').where.not(domaine_fonctionnel: nil).where('date >= ? AND date <= ? AND type_ae = ? AND (compte_budgetaire != ? AND compte_budgetaire != ? AND compte_budgetaire != ?)', @date, @date + 1.year,@type_ae, "21","22","23").sum('montant').to_i
          end 
  
          @bops = @chorus.select { |choru| choru.centre_financier.count("-") == 1 } #tous les bops du programme  
          #compter le nombre de bop differents 
          @bop_arr = []
          @bops.each do |bop|
            @bop_arr << bop.centre_financier
          end 
          @bop_arr.uniq!
          @bops_show = [@bop_arr[0]]
          @bop = Choru.where('type_ae = ? AND centre_financier = ? AND date >= ? AND date < ? AND compte_budgetaire = ?',@type_ae, @bop_arr[0],@date, @date + 1.year, @budget).order('date ASC')
          @type_pieces_bop=[]
          if !@bop.nil?
            @bop.each do |choru|
              @type_pieces_bop << choru.type_piece
            end 
            @type_pieces_bop.uniq! 
          end

          #compter le nombre de uo differents du bop selecionne
          @uo_search = @bop_arr[0] + '-'
          @uos = Choru.where('type_ae = ? AND compte_budgetaire = ?',@type_ae, @budget).where('centre_financier like ? ', '%'+@uo_search+'%').order('date ASC')
          @uo_arr = []
          @uos.each do |uo|
            @uo_arr << uo.centre_financier
          end 
          @uo_arr.uniq! 
          @uos_show = [@uo_arr[0]]
          @uo = Choru.where('type_ae = ? AND centre_financier = ?  AND date >= ? AND date < ? AND compte_budgetaire = ?',@type_ae, @uo_arr[0],@date, @date + 1.year, @budget ).order('date ASC') #on choisit dafficher le premier uo      
          @type_pieces_uo=[]
          if !@uo.nil?
            @uo.each do |choru|
              @type_pieces_uo << choru.type_piece
            end 
            @type_pieces_uo.uniq! 
          end

         #nombre d'actions 
          @uo_actions = []
          Choru.where('centre_financier = ? AND date >= ? AND date < ? AND type_ae = ?',@uo_arr[0],@date, @date + 1.year, @type_ae).where.not(domaine_fonctionnel: nil).each do |uo|
            @uo_actions << [@uo_arr[0], uo.domaine_fonctionnel]
          end 
          @uo_actions.uniq!
          @uo_action = @uo_actions[0]
          if !@uo_actions[0].nil?
          @actions_show = [@uo_actions[0]]
          else
            @actions_show = []
          end
          @chorusconso = Chorusconso.where('centre_financier = ? AND action = ?',@uo_arr[0], @uo_action ).order('date ASC')
        end
      end
    else
      redirect_to chorus_path 
    end
  end 

  def select_bop
    @dates = params[:date]
    @vision = params[:vision]
    @budget = params[:budget]
    @type_ae = params[:type_ae]
    #@bop = Choru.where('centre_financier = ?', params[:id]).order('date ASC')
    @bop = Choru.where('date = ?', Date.new(1000))
    @uo = Choru.where('date = ?', Date.new(1000))
    @uos = Choru.where('date = ?', Date.new(1000))
    @search = params[:programme]
    
   
    @bops_show = params[:id]
   
    #on va rassembler tous les elements des bop pour savoir le nombre de piece
    params[:id].each do |id|
    params[:date].each do |date|
      @date = Date.new(date.to_i-1,12,1) 
      @bop = @bop.or(Choru.where('type_ae = ? AND centre_financier = ? AND date >= ? AND date < ? AND compte_budgetaire = ?', @type_ae, id,@date, @date + 1.year, @budget ))
    end
    end
    @type_pieces_bop=[]
      if !@bop.nil?
        @bop.each do |choru|
          @type_pieces_bop<< choru.type_piece
        end 
        @type_pieces_bop.uniq! 
      end
   
    @uo_search = []
    @bops_show.each do |bop|
      @uo_search << bop + '-'
    end
    @uo_search.each do |uo_search|
    @uos = @uos.or(Choru.where('centre_financier like ? ', '%'+uo_search+'%'))
    end
    @uo_arr = []
    @uos.each do |uo|
      @uo_arr << uo.centre_financier
    end 
    @uo_arr.uniq! #toutes les uo des bop
    @uos_show = [@uo_arr[0]] #on affiche que la premiere
  
    params[:date].each do |date|
      @date = Date.new(date.to_i-1,12,1)
      @uo = @uo.or(Choru.where('type_ae = ? AND centre_financier = ?  AND date >= ? AND date < ? AND compte_budgetaire = ?',@type_ae, @uo_arr[0],@date, @date + 1.year, @budget ))
    end
    @uo = @uo.order('date ASC')
    @type_pieces_uo=[]
      if !@uo.nil?
        @uo.each do |choru|
          @type_pieces_uo << choru.type_piece
        end 
        @type_pieces_uo.uniq! 
      end
     
    #nombre d'actions 
      @uo_actions = []
      Choru.where('centre_financier = ? AND date >= ? AND date < ?', @uo_arr[0],@date, @date + 1.year).where.not(domaine_fonctionnel: nil).each do |uo|
        @uo_actions << [@uo_arr[0], uo.domaine_fonctionnel]
      end 
      @uo_actions.uniq!
      @uo_action = @uo_actions[0]
      if !@uo_actions[0].nil?
      @actions_show = [@uo_actions[0]]
      else
        @actions_show = []
      end
    @chorusconso = Chorusconso.where('centre_financier = ? AND action = ?',@uo_arr[0], @uo_action ).order('date ASC')
  end 
  
  def select_uo
    @dates = params[:date]
    @budget = params[:budget]
    @vision = params[:vision]
    @uo = Choru.where('date = ?', Date.new(1000))
    @uos = Choru.where('date = ?', Date.new(1000))
    @bops_show = params[:bop_id] 
    @search = params[:programme]
    @type_ae = params[:type_ae]
    @uo_search = []
    @bops_show.each do |bop|
      @uo_search << bop + '-'
    end
    @uo_search.each do |uo_search|
    @uos = @uos.or(Choru.where('centre_financier like ? ', '%'+uo_search+'%'))
    end
    @uo_arr = []
    @uos.each do |uo|
      @uo_arr << uo.centre_financier
    end 
    @uo_arr.uniq! #toutes les uo des bops
   
    @uos_show = params[:id]
   
    @uos_show.each do |uo|
    params[:date].each do |date|
      @date = Date.new(date.to_i-1,12,1)
      @uo = @uo.or(Choru.where('type_ae = ? AND centre_financier = ?  AND date >= ? AND date < ? AND compte_budgetaire = ?',@type_ae, uo,@date, @date + 1.year, @budget ))
    end
    end
    @uo = @uo.order('date ASC')
    
    @type_pieces_uo=[]
      if !@uo.nil?
        @uo.each do |choru|
          @type_pieces_uo << choru.type_piece
        end 
        @type_pieces_uo.uniq! 
      end
     
    #nombre d'actions 
      @uo_actions = []
      @uos_show.each do |uo_show|
      Choru.where('centre_financier = ? AND date >= ? AND date < ?',uo_show,@date, @date + 1.year).where.not(domaine_fonctionnel: nil).each do |uo|
        @uo_actions << [uo_show, uo.domaine_fonctionnel]
      end 
      end
      @uo_actions.uniq!
      @uo_action = @uo_actions[0]
      if !@uo_actions[0].nil?
      @actions_show = [@uo_actions[0]]
      else
        @actions_show = []
      end

app/helpers/chorus_helper.rb
module ChorusHelper
end

app/views/chorus/_actions.html.erb
<% if  !@actions_show.empty?%>
<div class="box_page">
<div><span class="titre_section">Visualisation au niveau des actions des UO (<%= @uo_actions.length %>)</span></div>
<div class="i32"></div>
   <div class="chorus-dropdown-box">
   <div class="dropdown dropdown-chorus">
     <button class="btn btn-secondary dropdown-toggle dropdown-select-chorus" type="button" id="dropdownMenuButtonaction" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sélectionner une action <i class="fas fa-chevron-down"></i></button>
      <div class="dropdown-menu dropwdown-menu-chorus" aria-labelledby="dropdownMenuButtonaction">
          <%= form_with url: select_action_path(:uo_id => @uos_show, :date => @dates, :budget => @budget, :programme => @search), id: "action_form" do |f|%>
        <label><%= f.check_box :searchaction,{:multiple => true}, @search, nil %> Tout sélectionner </label>
        <% (0..@uo_actions.length-1).each do |i|%>
          <label><%= f.check_box :id,{:multiple => true},[@uo_actions[i][0],@uo_actions[i][1]] ,nil %>  <%= @uo_actions[i][0]%> - <%= @uo_actions[i][1]%> <% if ChorusNomenclature.where('nom = ?',@uo_actions[i][1]).count > 0 %>(<%= ChorusNomenclature.where('nom = ?',@uo_actions[i][1]).first.designation %>)<%end%></label>
        <% end %>
        <div class="chorus-submit-form"><%= f.submit "Afficher", class: "bouton bouton-action"%></div>
       <% end %>
      </div>
    </div>
  </div> 
  <div id="actions2">
     <%= render 'chorus/actions2'%>
  </div>
 

</div>


<script>
  var elementactionid = '#id_'+'<%= @uo_action[0].downcase %>'+'_'+'<%= @uo_action[1].downcase%>'
  $(elementactionid).prop('checked', true);

</script>
<script>
    var searchaction = '#searchaction_' + '<%= @search %>';

$(searchaction).click(function () {
  if ($(searchaction).is(':checked')){
   <% @uo_actions.each do |action|%>
      $('#id_'+'<%= action[0].downcase%>'+'_'+'<%= action[1].downcase%>').prop('checked', true);
   <% end %> 
  }
  else {
   <% @uo_actions[1..].each do |action|%>
      $('#id_'+'<%= action[0].downcase%>'+'_'+'<%= action[1].downcase%>').prop('checked', false);
   <% end %>  
    
  }
  
});
$('.bouton-action').on("click",function(){  
   $("#dropdownMenuButtonaction").dropdown('toggle');
});
</script>
 <% end %>

app/views/chorus/_uo_bloc.html.erb
<% if !@uo.nil? &&  !@uo.first.nil?%>
<div class="box_page" id="dynamique-uo">
  <div><span class="titre_section"><% if @vision == "0" || @vision == "2"%>Visualisation de la consommation et des crédits ouverts<%else%>Visualisation des mouvements de crédits<%end%> au niveau des UO (<%= @uo_arr.length %>)</span>     
  </div>
  <div class="i32"></div>
  <div class="chorus-dropdown-box">
   <div class="dropdown dropdown-chorus">
     <button class="btn btn-secondary dropdown-toggle dropdown-select-chorus" type="button" id="dropdownMenuButtonuo" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sélectionner une UO <i class="fas fa-chevron-down"></i></button>
      <div class="dropdown-menu dropwdown-menu-chorus" aria-labelledby="dropdownMenuButtonuo">
          <%= form_with url: select_uo_path(:bop_id => @bops_show, :date => @dates,:vision => @vision, :budget => @budget,:type_ae => @type_ae, :programme => @search), id: "uo_form" do |f|%>
          <label><%= f.check_box :searchuo,{:multiple => true}, @search, nil %> Tout sélectionner </label>
          <% (0..@uo_arr.length-1).each do |i|%>
            <label><%= f.check_box :id,{:multiple => true}, @uo_arr[i], nil %>  <%= @uo_arr[i]%> <% if ChorusNomenclature.where('nom = ?',@uo_arr[i]).count > 0 %>(<%= ChorusNomenclature.where('nom = ?',@uo_arr[i]).first.designation %>)<%end%></label>
          <% end %>
        <div class="chorus-submit-form"><%= f.submit "Afficher", class: "bouton bouton-uo"%></div>
         <% end %>
      </div>
    </div>
  </div>  
  <div id="uo">
    <%= render 'chorus/uo'%>
  </div>
</div>
<div class="i24"></div>
<!-- <div id="actions">-->
   <!--  render 'chorus/actions' -->
</div>  



<script>
  var elementuoid = '#id_'+'<%= @uo.first.centre_financier.downcase%>'
  $(elementuoid).prop('checked', true);

</script>

<script>
    var searchuoid = '#searchuo_' + '<%= @search %>';

$(searchuoid).click(function () {
  if ($(searchuoid).is(':checked')){
   <% @uo_arr.each do |uo|%>
      $('#id_'+'<%= uo.downcase%>').prop('checked', true);
   <% end %> 
  }
  else {
   <% @uo_arr[1..].each do |uo|%>
      $('#id_'+'<%= uo.downcase%>').prop('checked', false);
   <% end %>  
    
  }
  
});
$('.bouton-uo').on("click",function(){  
   $("#dropdownMenuButtonuo").dropdown('toggle');
});
</script>
<% end %>

app/views/chorus/index.html.erb
<div class="logo-ministere inline-flex">
  <%= image_tag 'logo_ministere.png'%>
</div>
<div class="page_w">
  <div class="box_page">
    <h1 class="titre_page text-center">DataChorus</h1>
  
    <div class="i40"></div>
    <div class="i40"></div>
    <%= form_tag search_choru_path, method: :get  do%>
    <%= search_form_for @q, url: search_choru_path do |f| %>

      <div class="text-center w100">
        
          <div class="chorus-search-box-form">
          <%= f.search_field :centre_financier_cont,class: "form-field", id:"name",required: true, placeholder: "Entrer le numéro d'un programme", data: {autocomplete_source: chorus_path} %> 
          <a type="button" class="choru-search-submit"> <i class="fas fa-search"></i><span class="hidden-xs hidden-sm">Liste programme</span></a>
          </div> 
          <div class="chorus-search-box-form-list" id="programme-liste">
            <div style="text-align:left;">  
            <% if !@liste_programme.nil?%>
              <% @liste_programme.each do |programme| %>
              <div class="liste-programme-name"><a class="programme-name"><%= programme %> <% if ChorusNomenclature.where('nom = ?',programme).count > 0 %>- <%= ChorusNomenclature.where('nom = ?',programme).first.designation %><%end%></a></div>
              <% end %>
            <% end %>                   
            </div>
          </div>
      </div>
      
   
    <div class="i60"></div>

      <div class="text-center w100">
        <div class="inline-flex">
          <div class="form form-chorus">
            <label>Vision</label>
            <%= select_tag :vision, options_for_select([["Suivi consommation","0"],["Allocation des ressources","1"]]), {prompt:"- Sélectionner -"} %>
     
          </div>
          <div class="form form-chorus">
            <label>AE/CP</label>
            <%= select_tag :type_ae, options_for_select([["CP","cp"],["AE","ae"]]), {prompt:"- Sélectionner -"} %>
     
          </div>
          <div class="form form-chorus">
            <label>HT2/T2</label>
            <%= select_tag :budget, options_for_select([["HT2","HT2"],["T2","T2"]]), {prompt:"- Sélectionner -"} %>
     
          </div>
          <div class="form form-chorus">
            <label>Année</label>
            <%= select_tag :dates, options_for_select([["2020","2020"]]), {prompt:"- Sélectionner -"} %>
     
          </div>
   
         
        </div>
      </div>
      <div class="i60"></div>
      <div class='text-center'>
          <%= button_tag(type: "submit",class:'bouton') do %><i class="fas fa-search"></i> Rechercher <% end %>
      </div>
 
    <% end %>
    <% end %>
    <div class="i40"></div>
  </div>
</div>

<div class='background'>
<%= render 'layouts/footer'%>
</div>

<script>

  $(function() {
 // var matieres = ["Stade de france", "Arena 2", "village"]
  // Below is the name of the textfield that will be autocomplete    
    $('#name').autocomplete({
 // This is the source of the auocomplete suggestions. In this case a list of names from the people controller, in JSON format.
     
      source: $('#name').data('autocomplete-source'),
          //  source:matieres,
           
      select: function(event, ui) {
       // $.ajax({
       //   type:'GET',
       //   url: '/ouvrages',
          
        //});
        $("#name").val(ui.item.label);
          $("#submit_button").click()    

    },
        })
     .data("ui-autocomplete")._renderItem = function(ul, item){
       var expression = new RegExp(this.term, "gi");
      var result = expression.exec(item.label);
      var answer; 
      if (result.index == 0){
        answer = item.label.replace(expression, "<span style='font-weight:bold;color:#000091'>" + this.term + "</span>");
        return $("<li></li>")
      .append("<a>"+answer+"</a>")
      .prependTo(ul);
      }   
      else
       answer = item.label.replace(expression, "<span style='font-weight:bold;color:#000091'>" + this.term.toLowerCase() + "</span>");
      return $("<li></li>")
      .append("<a>"+answer+"</a>")
      .appendTo(ul);
     
    };
    
  });
</script>

<script>
$('#programme-liste').hide();
 $('.choru-search-submit').click(function(){
   if ($('#programme-liste').is(":visible")){
     $('#programme-liste').hide();
   } else {
     $('#programme-liste').show();
   }   
 });
  
 $('.programme-name').click(function(){
  $("#name").val($(this).text());
  $('#programme-liste').hide();
 });
</script>

app/views/chorus/select_action.js.erb
$('#actions2').html("<%= j render 'chorus/actions2'%>");

app/views/chorus/select_actions.js.erb
$('#actions').html("<%= j render 'chorus/actions'%>");

app/views/chorus/select_bop.js.erb
$('#bop').html("<%= j render 'chorus/bop'%>");
$('#tableau_bop').html("<%= j render 'chorus/tableau_bop'%>");

$('#uo_bloc').html("<%= j render 'chorus/uo_bloc'%>");